export const PLAYER_CAPSULE_HALF_HEIGHT = 0.55
export const PLAYER_RADIUS = 0.35
export const PLAYER_SPAWN: [number, number, number] = [0, 2, 0]
export const PLAYER_SPEED = 5
export const PLAYER_JUMP_SPEED = 7
export const PLAYER_GROUNDED_HEIGHT =
  PLAYER_CAPSULE_HALF_HEIGHT + PLAYER_RADIUS + 0.05
export const PLAYER_MAX_GROUNDED_DOWNWARD_SPEED = 0.2

export const PROJECTILE_SPEED = 26
export const PROJECTILE_RADIUS = 0.14
export const PROJECTILE_LIFESPAN_MS = 2500
export const PROJECTILE_COOLDOWN_MS = 300
export const PROJECTILE_SPAWN_FORWARD_OFFSET = 0.6
export const PROJECTILE_SPAWN_HEIGHT = 0.55

export const CAMERA_DISTANCE = 7
export const CAMERA_HEIGHT = 2.1
export const CAMERA_FOLLOW_SMOOTHING = 7
export const CAMERA_ROTATION_SENSITIVITY = 0.006
export const CAMERA_MIN_PITCH = -0.2
export const CAMERA_MAX_PITCH = 0.45
